### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by howdoicomputer** [ysbaddaden/shards#38] opened 2015-09-19 21:32 UTC
Is this planned? I tried getting started but compile errors.

```
➜  shards git:(master) crystal build src/shards.cr
ld: library not found for -lyaml
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o "shards" "${@}"  -rdynamic  -lyaml -levent -lpcl -lpcre -lgc -lpthread -ldl`
```

Thought I would try this language out and tinker with Moonshards but I couldn't get shards installed. When I get home I'll install it on my Arch box but, you know.

**Comment by jhass** [comment] 2015-09-19 21:34
That means you don't have libyaml installed, try `brew install libyaml`

**Comment by howdoicomputer** [comment] 2015-09-19 21:40
@jhass ➜  test git:(master) ✗ brew install libyaml
Warning: libyaml-0.1.6_1 already installed

**Comment by jhass** [comment] 2015-09-19 21:43
`brew doctor`? Idk, I don't use OS X

**Comment by ysbaddaden** [comment] 2015-09-19 22:02
I'm afraid I can't help either. I'm not on Mac and Travis succeeds to build it: https://travis-ci.org/ysbaddaden/shards/jobs/81046976 But maybe libyaml is already installed.

**Comment by howdoicomputer** [comment] 2015-09-19 22:06
I found a closed issue that fixed my problem: https://github.com/ysbaddaden/shards/issues/14

**Comment by howdoicomputer** [comment] 2015-09-19 22:35
I opened a pull request to improve the documentation for future hackers trying to get started. Let me know if anything is needed.

**Comment by ysbaddaden** [comment] 2015-09-19 22:42
Closing since duplicate of #14

**Closed by ysbaddaden** 2015-09-19 22:42 UTC
