### ISSUE TITLE
libs folder has libraries from outdated `shards.yml`.

### ISSUE THREAD

**Issue by vjdhama** [ysbaddaden/shards#83] opened 2016-01-04 17:45 UTC
I created a crystal lib and added a development_dependency in `shards.yml`. Now I removed that dependency, but the fetched lib still stays inside libs folder of the project. Is this expected behavior?

**Comment by luislavena** [comment] 2016-01-04 19:28
@vjdhama I believe there is no purge of removed libraries unless manual removal is done (at this time).

Hope that helps.

**Comment by luislavena** [comment] 2016-01-04 19:32
See #57

**Comment by ysbaddaden** [comment] 2016-01-04 21:42
Yes, this is the expected behavior. I actually follow other package managers like Bower or Bundler that don't clean up until they're told so.

**Comment by ysbaddaden** [comment] 2016-01-04 21:43
Duplicate of #78

**Closed by ysbaddaden** 2016-01-04 21:42 UTC
